---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: forge-os
description: This is my personal OS image, derived from https://github.com/wayblueorg/wayblue

base-image: ghcr.io/wayblueorg/river
image-version: latest

modules:
  - type: dnf
    repos:
      copr:
        - atim/starship
    group-install:
      packages:
        - development-tools
    install:
      packages:
        - bazaar
        - flac
        - fscrypt
        - libffi-devel
        - openssl-devel
        - podman-compose
        - podman-docker
        - qutebrowser
        - starship
        - tealdeer
        - tmux
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - scope: system
        notify: false
        install:
          - com.github.rafostar.Clapper
          - com.github.tchx84.Flatseal
          - com.usebottles.bottles
          - com.visualstudio.code
          - io.github.dvlv.boxbuddyrs
          - io.github.flattool.Warehouse
          - io.missioncenter.MissionCenter
          - io.mpv.Mpv
          - io.podman_desktop.PodmanDesktop
          - org.atheme.audacious
          - org.audacityteam.Audacity
          - org.gnome.Boxes
          - org.gnome.Loupe
          - org.kde.gwenview
          - org.kde.krita
          - org.mozilla.firefox
      - scope: user
        notify: false

  - type: os-release
    properties:
      NAME: "ForgeOS"
      ID: forgeos
      ID_LIKE: "fedora"
      PRETTY_NAME: "ForgeOS"
      DEFAULT_HOSTNAME: "forgeos"
      HOME_URL: "https://forgeos.appsmith.uk/"
      DOCUMENTATION_URL: "https://github.com/arti5an/forge-os"

  - type: signing
